version: '3.7'
services:
  doodle:
    container_name: doodle
    image: doodle
    build: ./doodle
    ports:
      - '8005:8005'
    volumes:
      - './doodle/src:/app/src/'
    networks:
      - doodle
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=test
      - DATABASE_DATABASE=test
      - DATABASE_HOST=mysqldb
      - DATABASE_ENTITY_PREFIX=doodle_
      - API_PORT=8005
      - NOODLE_URL=http://noodle:8006/noodle
    links:
      - noodle
    depends_on:
      - noodle
  noodle:
    container_name: noodle
    image: noodle
    build: ./noodle
    ports:
      - '8006:8006'
    volumes:
      - './noodle/src:/app/src/'
    networks:
      - doodle
    environment:
      - API_PORT=8006  
networks:
  doodle:
    external:
      name: doodle
